apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: devopshint
          image: 979578978884.dkr.ecr.us-east-2.amazonaws.com/docker_nodejs_demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
